name: Start Hotfix

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  __APP_ENV: "hotfix"
  # https://nx.dev/troubleshooting/unknown-local-cache#you-share-cache-with-another-machine-using-a-network-drive
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

jobs:
  start-hotfix:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a Git App installe token
        id: generate-token
        uses: actions/create-github-app-token@v1.12.0
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: "${{ github.repository_owner }}"
         # repositories: ${{ github.repository }}
#          repositories: new-git-workflow
          repositories: ${{ github.event.repository.name }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: true

      - name: set latest release tag
        run: |
          echo "LATEST_RELEASE_TAG=$(git tag | grep -E '^v[0-9]+[.][0-9]+[.][0-9]+$' | sort -V | tail -n 1)" >> "$GITHUB_ENV"

      - name: Checkout and Push 'hotfix/base'
        run: |
          git checkout -b hotfix/base "${LATEST_RELEASE_TAG}"
          git push -f origin hotfix/base
  
      - name: setup runtime
        uses: ./.github/actions/setup/
          
      # hotfix環境を作成
      - name: deploy
        run: APP_ENV=$__APP_ENV npx nx run-many --verbose --target deploy --all

